version: '3'

services:
  front:
    build:
      context: ./front
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - certs:/etc/nginx/certs
      - letsencrypt:/var/www/letsencrypt
    environment:
      BUILDER_HOSTNAME: 103.128.221.202.static.iijgio.jp

  cert:
    build:
      context: ./cert
    volumes:
      - certs:/etc/letsencrypt
      - letsencrypt:/var/www/letsencrypt

  jenkins:
    build:
      context: ./jenkins
    restart: always
    entrypoint: /bin/tini --
    command: sh -c 'sudo redis-server /etc/redis/redis.conf; sudo redis-server --daemonize yes --port 6380 --requirepass secret; /usr/local/bin/jenkins.sh'
    environment:
      JENKINS_OPTS: --prefix=/jenkins
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
    volumes:
      - jenkins_home:/var/jenkins_home

volumes:
  jenkins_home:
  certs:
  letsencrypt:
