version: '2'

services:
  front:
    image: nginx:1.13-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./mounts/certs:/etc/nginx/certs
      - ./mounts/letsencrypt:/var/www/letsencrypt
      - ./front:/etc/nginx/conf.d
    environment:
      BUILDER_HOSTNAME: 103.128.221.202.static.iijgio.jp

  cert:
    build: ./cert
    volumes:
      - ./mounts/certs:/etc/letsencrypt
      - ./mounts/letsencrypt:/var/www/letsencrypt

  builder:
    build: ./builder
    image: mrbgems/mrubybuilder
    command: tail -f /dev/null

  jenkins:
    build: ./jenkins
    entrypoint: /bin/tini --
    command: sh -c 'sudo chown jenkins:jenkins /var/run/docker.sock; /usr/local/bin/jenkins.sh'
    environment:
      JENKINS_OPTS: --prefix=/jenkins
    volumes:
      - ./mounts/jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
